### ISSUE TITLE
Toggle Numbers

### ISSUE THREAD

**Issue by ironfish** [ckipp01/dots#1]
I'm trying our nvim-metals and am using your dots as an example. In your `settings.functions` you have a function for toggle numbers. I have this setup with the following mapping:

`map("n", "<leader>n", [[<cmd>lua RELOAD("settings.functions").toggle_nums()<CR>]])`

However when I use `<leader>n` I get the following Lua error which I cannot figure out:

`E5108: Error executing Lua [string ":Lua"]:1: attempt to call global 'RELOAD' (a nil value)`

Any help would be much appreciated.

**Comment by ironfish** [comment]
Okay, by changing the mapping to:

`map("n", "<leader>n", [[<cmd>lua require("settings.functions").toggle_nums()<CR>]])`

it now works.

I'll leave the issue open for your review.

**Comment by ckipp01** [comment]
Hey @ironfish, `RELOAD` is actually a little trick I use to actually reload the lua module that you're calling on every call. You can see it's defined here:

https://github.com/ckipp01/dots/blob/93aac0f78721e892704679731552f74de6cea1af/nvim/.config/nvim/lua/playground/globals.lua#L6-L9

I do this so when I'm working on stuff, you can be making changes in the module and never have to close NeoVim in order for your changes to take effect. Instead, it drops reference to it, requires it, and then calls it. It's fast enough to do that.

I include these globals in my init here:

https://github.com/ckipp01/dots/blob/93aac0f78721e892704679731552f74de6cea1af/nvim/.config/nvim/init.lua#L139

**Comment by ironfish** [comment]
Thanks @ckipp01. I didn't think to look in the playgrounds folder.
